/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package DBConnect;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author roy
 */
public class MarksfromDB extends javax.swing.JFrame {

    /**
     * Creates new form MarksfromDB
     */
    public MarksfromDB() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param termexam
     * @param clas
     */
    public void marksOfclass(String termexam, String clas){
        Connection con = null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/schoolmgmt","root","");
            System.out.println("Connection successfull!");
            String names, password;
            int termExam = Integer.parseInt(termexam);
            int standard = Integer.parseInt(clas);
            ResultSet resltset = null;
            Statement smnt = con.createStatement();
            String eng = "english";
            resltset =smnt.executeQuery("select e.username, e.password, er.studentid, er.om"+
                    " "+"from accounts e, "+eng+" er");
            System.out.println("yasamma thik chha");
            while(resltset.next())
            {
                names = resltset.getString(1);
                password = resltset.getString(2);
//                stdid = resltset.getInt("studentid");
//                om = resltset.getInt("om");
//                System.out.println(names+" has set "+password+" as password and id "
//                        + " and om is"+stdid+om);
            }
            JOptionPane.showMessageDialog(null,"Record Saved Successfully!");
        
        } catch (SQLException ex) {
            System.err.println("Unable to load driver!");
            Logger.getLogger(MarkstoDB.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
